"""
Django settings for application project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ================================================= #
# ******************** Configuration dynamique ******************** #
# ================================================= #

from conf.env import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Overridable via the DJANGO_SECRET_KEY env var. Booting with DEBUG=False
# and the bundled development key is refused (see guard below).
_DEV_SECRET_KEY = "django-insecure--z8%exyzt7e_%i@1+#1mm=%lb5=^fx_57=1@a+_y7bg5-w%)sm"
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", locals().get("SECRET_KEY", _DEV_SECRET_KEY))
# Initialiser le chemin des plugins dans les variables d'environnement
PLUGINS_PATH = os.path.join(BASE_DIR, "plugins")
sys.path.insert(0, os.path.join(PLUGINS_PATH))

[
    sys.path.insert(0, os.path.join(PLUGINS_PATH, ele))
    for ele in os.listdir(PLUGINS_PATH)
    if os.path.isdir(os.path.join(PLUGINS_PATH, ele)) and not ele.startswith("__")
]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = locals().get("DEBUG", True)
_allowed_hosts_env = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
else:
    ALLOWED_HOSTS = locals().get("ALLOWED_HOSTS", ["*"])

if not DEBUG:
    # Fail closed in production: refuse dev secrets / open hosts.
    from django.core.exceptions import ImproperlyConfigured

    if SECRET_KEY == _DEV_SECRET_KEY:
        raise ImproperlyConfigured(
            "Refusing to start with the bundled development SECRET_KEY. "
            "Set the DJANGO_SECRET_KEY environment variable."
        )
    if ALLOWED_HOSTS == ["*"]:
        raise ImproperlyConfigured(
            "Refusing to start with ALLOWED_HOSTS=['*'] in production. "
            "Set the DJANGO_ALLOWED_HOSTS environment variable."
        )
    # HTTPS / cookie hardening (assumes TLS is terminated at the edge/proxy).
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "DENY"
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_comment_migrate",
    "rest_framework",
    "django_filters",
    "corsheaders",  # Enregistrer l'app CORS
    'rest_framework_simplejwt.token_blacklist',
    "dvadmin.system",
    "drf_yasg",
    "captcha",
    'channels',
]

MIDDLEWARE = [
    "dvadmin.utils.middleware.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # Middleware CORS
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "dvadmin.utils.middleware.ApiLoggingMiddleware",
]

ROOT_URLCONF = "application.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "application.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": DATABASE_ENGINE,
        "NAME": DATABASE_NAME,
        "USER": DATABASE_USER,
        "PASSWORD": DATABASE_PASSWORD,
        "HOST": DATABASE_HOST,
        "PORT": DATABASE_PORT,
    }
}
AUTH_USER_MODEL = "system.Users"
USERNAME_FIELD = "username"

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
# # Définir le répertoire des fichiers statiques de Django
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_ROOT = os.path.join(BASE_DIR, "media")  # Répertoire sous le projet (absolute path)
MEDIA_URL = "/media/"  # Similaire à STATIC_URL, les utilisateurs peuvent retrouver les fichiers via cette url

# Collecter les fichiers statiques, commenter d'abord MEDIA_ROOT,STATICFILES_DIRS
# python manage.py collectstatic
# STATIC_ROOT=os.path.join(BASE_DIR,'static')

# ================================================= #
# ******************* Configuration CORS ******************* #
# ================================================= #

# Autoriser toute la configuration (dev only by default; see CORS_ALLOW_ALL / CORS_ALLOWED_ORIGINS env vars)
_cors_allow_all = os.environ.get("CORS_ALLOW_ALL", "true" if DEBUG else "false").lower() in ("1", "true", "yes")
CORS_ORIGIN_ALLOW_ALL = _cors_allow_all  # django-cors-headers < 3.13
CORS_ALLOW_ALL_ORIGINS = _cors_allow_all  # django-cors-headers >= 3.13
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",") if o.strip()
]
# Autoriser les cookies
CORS_ALLOW_CREDENTIALS = True  # Indique si le backend prend en charge les cookies lors des accès inter-domaines

# ================================================= #
# ********************* Configuration channels ******************* #
# ================================================= #
ASGI_APPLICATION = 'application.asgi.application'
if not locals().get('REDIS_HOST', ""):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
else:
    REDIS_URL = locals().get('REDIS_URL', "")
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [(REDIS_URL)],  # À modifier
            },
        },
    }

# # ================================================= #
# # ********************* Configuration des journaux ******************* #
# # ================================================= #
# # Début de la partie configuration des logs #
SERVER_LOGS_FILE = os.path.join(BASE_DIR, "logs", "server.log")
ERROR_LOGS_FILE = os.path.join(BASE_DIR, "logs", "error.log")
LOGS_FILE = os.path.join(BASE_DIR, "logs")
if not os.path.exists(os.path.join(BASE_DIR, "logs")):
    os.makedirs(os.path.join(BASE_DIR, "logs"))

# Format :[2020-04-22 23:33:01][micoservice.apps.ready():16] [INFO] Ceci est un journal :
# Format :[date][module.nom_fonction():ligne] [niveau] info
STANDARD_LOG_FORMAT = (
    "[%(asctime)s][%(name)s.%(funcName)s():%(lineno)d] [%(levelname)s] %(message)s"
)
CONSOLE_LOG_FORMAT = (
    "[%(asctime)s][%(name)s.%(funcName)s():%(lineno)d] [%(levelname)s] %(message)s"
)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {"format": STANDARD_LOG_FORMAT},
        "console": {
            "format": CONSOLE_LOG_FORMAT,
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "file": {
            "format": CONSOLE_LOG_FORMAT,
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": SERVER_LOGS_FILE,
            "maxBytes": 1024 * 1024 * 100,  # 100 MB
            "backupCount": 5,  # Sauvegarder au plus 5 éléments
            "formatter": "standard",
            "encoding": "utf-8",
        },
        "error": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": ERROR_LOGS_FILE,
            "maxBytes": 1024 * 1024 * 100,  # 100 MB
            "backupCount": 3,  # Sauvegarder au plus 3 éléments
            "formatter": "standard",
            "encoding": "utf-8",
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "console",
        },

    },
    "loggers": {
        "": {
            "handlers": ["console", "error", "file"],
            "level": "INFO",
        },
        "django": {
            "handlers": ["console", "error", "file"],
            "level": "INFO",
            "propagate": False,
        },
        'django.db.backends': {
            'handlers': ["console", "error", "file"],
            'propagate': False,
            'level': "INFO"
        },
        "uvicorn.error": {
            "level": "INFO",
            "handlers": ["console", "error", "file"],
        },
        "uvicorn.access": {
            "handlers": ["console", "error", "file"],
            "level": "INFO"
        },
    },
}

# ================================================= #
# *************** Configuration REST_FRAMEWORK *************** #
# ================================================= #

REST_FRAMEWORK = {
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",  # Configuration du format date-heure
    "DATE_FORMAT": "%Y-%m-%d",
    "DEFAULT_FILTER_BACKENDS": (
        # 'django_filters.rest_framework.DjangoFilterBackend',
        "dvadmin.utils.filters.CustomDjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "dvadmin.utils.pagination.CustomPagination",  # Pagination personnalisée
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",  # Accès réservé aux utilisateurs authentifiés
        # 'rest_framework.permissions.IsAdminUser', # is_staff=True requis pour l'accès —— permission administrateur (employé)
        # 'rest_framework.permissions.AllowAny', # Tout autoriser
        # 'rest_framework.permissions.IsAuthenticatedOrReadOnly', # Avec identité ou accès en lecture seule(self.list,self.retrieve)
    ],
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/min",
        "user": "1000/min",
        "login": "10/min",
    },
    "EXCEPTION_HANDLER": "dvadmin.utils.exception.CustomExceptionHandler",  # Gestion personnalisée des exceptions
}
# ================================================= #
# ******************** Configuration du mode de connexion ******************** #
# ================================================= #

AUTHENTICATION_BACKENDS = ["dvadmin.utils.backends.CustomBackend"]
# ================================================= #
# ****************** Configuration simplejwt ***************** #
# ================================================= #
from datetime import timedelta

SIMPLE_JWT = {
    # Durée de validité du token
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    # Durée de validité après rafraîchissement du token
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    # Définir le préfixe
    "AUTH_HEADER_TYPES": ("JWT",),
    "ROTATE_REFRESH_TOKENS": True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# ====================================#
# ****************swagger************#
# ====================================#
SWAGGER_SETTINGS = {
    # Style de base
    "SECURITY_DEFINITIONS": {"basic": {"type": "basic"}},
    # Si une connexion est requise pour voir la doc API, utiliser le lien de connexion fourni par restframework.
    "LOGIN_URL": "apiLogin/",
    # 'LOGIN_URL': 'rest_framework:login',
    "LOGOUT_URL": "rest_framework:logout",
    # 'DOC_EXPANSION': None,
    # 'SHOW_REQUEST_HEADERS':True,
    # 'USE_SESSION_AUTH': True,
    # 'DOC_EXPANSION': 'list',
    # Trier la liste des méthodes par ordre alphabétique dans la doc API
    "APIS_SORTER": "alpha",
    # Si la soumission json est prise en charge, la doc API inclut une zone de saisie json
    "JSON_EDITOR": True,
    # Tri alphabétique de la liste des méthodes
    "OPERATIONS_SORTER": "alpha",
    "VALIDATOR_URL": None,
    "AUTO_SCHEMA_TYPE": 2,  # Regroupement selon le niveau d'url, 0, 1 ou 2 niveaux
    "DEFAULT_AUTO_SCHEMA_CLASS": "dvadmin.utils.swagger.CustomSwaggerAutoSchema",
}

# ================================================= #
# **************** Configuration du captcha  ******************* #
# ================================================= #
CAPTCHA_IMAGE_SIZE = (160, 60)  # Définir la taille de l'image captcha
CAPTCHA_LENGTH = 4  # Nombre de caractères
CAPTCHA_TIMEOUT = 1  # Expiration (minutes)
CAPTCHA_OUTPUT_FORMAT = "%(image)s %(text_field)s %(hidden_field)s "
CAPTCHA_FONT_SIZE = 40  # Taille de police
CAPTCHA_FOREGROUND_COLOR = "#64DAAA"  # Couleur de premier plan
CAPTCHA_BACKGROUND_COLOR = "#F5F7F4"  # Couleur d'arrière-plan
CAPTCHA_NOISE_FUNCTIONS = (
    "captcha.helpers.noise_arcs",  # Ligne
    # "captcha.helpers.noise_dots",  # Point
)
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge' #Captcha alphabétique
CAPTCHA_CHALLENGE_FUNCT = "captcha.helpers.math_challenge"  # Captcha d'opérations arithmétiques

# ================================================= #
# ******************** Autre configuration ******************** #
# ================================================= #

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
# Activer ou non la journalisation des API
API_LOG_ENABLE = locals().get("API_LOG_ENABLE", True)
# Captcha-less backdoor login endpoint (/api/token/). Testing only — always
# False unless explicitly enabled in local conf (never in production).
LOGIN_NO_CAPTCHA_AUTH = locals().get("LOGIN_NO_CAPTCHA_AUTH", False)
# Méthodes de requête journalisées pour les API
API_LOG_METHODS = locals().get("API_LOG_METHODS", ["POST", "UPDATE", "DELETE", "PUT"])
# API_LOG_METHODS = 'ALL' # ['POST', 'DELETE']
# Mappage des modules de requête journalisés en détail dans le journal des opérations
API_MODEL_MAP = locals().get("API_MODEL_MAP", {
    "/token/": "Module de connexion",
    "/api/login/": "Module de connexion",
    "/api/logout/": "Module de connexion",
})

DJANGO_CELERY_BEAT_TZ_AWARE = False
CELERY_TIMEZONE = "Asia/Shanghai"  # Problème de fuseau horaire celery
# Compression des pages statiques
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

ALL_MODELS_OBJECTS = []  # Tous les objets models des apps

# Liste à exécuter pour l'initialisation, exécutée après l'initialisation
INITIALIZE_LIST = []
INITIALIZE_RESET_LIST = []
# Préfixe des tables
TABLE_PREFIX = locals().get('TABLE_PREFIX', "")
# Configuration système
SYSTEM_CONFIG = {}
# Configuration du dictionnaire
DICTIONARY_CONFIG = {}

# ================================================= #
# ******************** Configuration des plugins ******************** #
# ================================================= #
# Apps partagées des tenants
TENANT_SHARED_APPS = []
# urlpatterns des plugins
PLUGINS_URL_PATTERNS = []
# ********** Début de la configuration d'import des plugins en un clic **********
# Par exemple :
# from dvadmin_upgrade_center.settings import *   # Centre de mise à niveau
# from dvadmin_celery.settings import *           # Tâches asynchrones celery
# from dvadmin_sms.settings import *              # Service SMS
# from dvadmin_third.settings import *            # Connexion par QR code
# from dvadmin_uniapp.settings import *           # Backend UniApp
# from dvadmin_ak_sk.settings import *            # Gestion des clés secrètes
# from dvadmin_tenants.settings import *          # Gestion des tenants
# from dvadmin_cloud_storage.settings import * # Stockage cloud
#from dvadmin_low_code_crud.settings import *  # Opérations low-code
# ...

# ********** Fin de la configuration d'import des plugins en un clic **********
